name: flutter_braintree
description: Flutter plugin that wraps the native Braintree SDKs. Enables payments with credit cards, PayPal, Google Pay and more.
version: 1.0.1
homepage: https://github.com/Pikaju/FlutterBraintree

environment:
  sdk: ">=2.2.2 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ">= 1.0.0 <2.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_braintree
        pluginClass: FlutterBraintreePlugin
      ios:
        pluginClass: FlutterBraintreePlugin