name: flutter_braintree
description: Flutter plugin that wraps the native Braintree SDKs. Enables payments with credit cards, PayPal, Google Pay and more.
version: 0.4.0
author: Julien Scholz <julienscholzo@hotmail.de>
homepage: https://github.com/Pikaju/FlutterBraintree

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ">= 1.0.0 <2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.example.flutter_braintree
    pluginClass: FlutterBraintreePlugin